### ISSUE TITLE
Have Eror in number 64

### ISSUE THREAD

**Issue by virusphp** [steveathon/php-linked-list#1]
b>Notice</b>:  Trying to get property of non-object in <b>C:\xampp\htdocs\tugas_pertama\linkedList.php</b> on line <b>64</b><br />
linkedListNode Object

**Comment by steveathon** [comment]
@virusphp Hrm, I didn't get this error when I re-ran it. Sorry for the 2 year response time on this issue. I'm going to close it but please feel free to re-open if it's still an issue.
